// build-with-angular/src/app/product/product.component.ts
import { Component } from '@angular/core';
import { ICut } from 'src/shared/interfaces/cut';
import { IProduct } from 'src/shared/interfaces/product';
import { ISelectedProduct } from 'src/shared/interfaces/selectedProduct';
import {products} from '../../assets/products';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.scss']
})
export class ProductComponent {
  products!: IProduct[];
  product!: IProduct;
  selected!: ISelectedProduct;

  constructor() {
    this.products = products;
    this.product = this.products[0];
  }

  selectHandler(cut: ICut) {
    this.selected = {
      mark: this.product.mark,
      model: this.product.models[0].title,
      type: this.product.models[0].type,
      ml: cut.ml,
      price: cut.price,
      weight: cut.weight,
      imgUrl: this.product.models[0].img
    };
  }
}

<div class="products">
    <div class="product-ctr">
      <div class="img-ctr">
        <img src="{{product.models[0].img}}" alt="">
      </div>
      <div class="product-description-ctr">
        <h1>{{product.mark}}</h1>
        <h2>{{product.models[0].title}}</h2>
        <span>{{product.models[0].type}}</span>
        <div class="product-cuts-ctr">
          <div (click)="selectHandler(cut)" *ngFor="let cut of product.models[0].cuts" class="cut-ctr">
            <span>{{cut.ml}} ml</span>
            <span><strong>{{cut.price}} lv</strong></span>
          </div>
        </div>
        <button [routerLink]="['/checkout', selected.mark, selected.model, selected.type, selected.ml, selected.price, selected.weight, selected.imgUrl]" *ngIf="selected">Checkout</button>
        <div class="choosen">
          <span *ngIf="selected">You'r choose: {{selected.ml}}ml - {{selected.price}}lv</span>
        </div>
        
      </div>
    </div>
  </div>

// build-with-react/src/components/Product/Product.tsx
import { Link, useNavigate } from "react-router-dom";
import { useState } from "react";
import { IProduct } from "../../interfaces/product";
import { ICut } from "../../interfaces/cut";

import {CutList} from "../CutList/CutList";

const Product = ({data}: {data: IProduct}) => {
    const navigate = useNavigate();

    const [product, setProduct] = useState<IProduct>({...data, selectedCut: data.models[0].cuts[0]});

    const onNavigateToCheckout = () => {
        navigate('/checkout', {state: product})
    }

    const onSelectCutHandler = (cut: ICut) => {
        setProduct(oldProduct => ({
            ...oldProduct,
            selectedCut: cut
        }))
    }

    return (
        <div className="product-ctr">
            <div className="img-ctr">
                <img src={data.models[0].img} alt="image" />
            </div>
            <div className="product-description-ctr">
                <h1>{data.mark}</h1>
                <h2>{data.models[0].title}</h2>
                <span>{data.models[0].type}</span>
                <CutList onSelectCutHandler={onSelectCutHandler} cuts={data.models[0].cuts} selectedCut={product.selectedCut!} />
                <button onClick={onNavigateToCheckout}>Checkout</button>
            </div>
        </div>
    )
}

export default Product;
